# Generated by Django 3.0.2 on 2020-01-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('Asn1', models.CharField(max_length=200)),
                ('Asn2', models.CharField(max_length=200)),
                ('Asn3', models.CharField(max_length=200)),
                ('Asn4', models.CharField(max_length=200)),
                ('TrueAns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_status', models.BooleanField()),
                ('q_numer', models.IntegerField()),
                ('tst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(through='questions.UserTest', to=settings.AUTH_USER_MODEL),
        ),
    ]
