# Generated by Django 3.0.2 on 2020-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='question_status',
            field=models.BooleanField(null=True),
        ),
    ]
